config/routes.rb
Rails.application.routes.draw do

  get "lists", to: "lists#index"
  get "lists/:id", to: "lists#show", as: :list
  get "lists/:id", to: "lists#new", as: :new

  get "lists/new", to: "lists#new"
  post "lists", to: "lists#create"

  delete "lists/:id", to: "lists#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :comment, length: { minimum: 6  }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
  end

  def show
    @list = List.find(params[:id])
  end

  def edit
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit "add movie", class: "btn btn-primary" %>
<% end %>

app/views/lists/index.html.erb
<ul>
  <% @lists.each do |list|  %>
    <li>
      <%= list.name %>
    </li>
  <% end %>
</ul>

<h1>Create your own list</h1>

<%= link_to 'Create', lists_new_path %>

app/views/lists/new.html.erb
<h1>Create a new list</h1>

<%= render :partial => "form", :object => f %>

<%# <%= form_for @list, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
<%#  <%= f.text_field :name %>
<%#  <%= f.text_area :body, size: "60x12" %>
<%#  <%= f.submit "Create" %>
<%#<% end %>
<%# Dropdown/Search bar for movies %>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>

<ul>
  <% @list.bookmarks.each do |list|  %>
    <li>
      <%= list.movie.title %>
      <%= list.movie.poster_url %>
    </li>
  <% end %>
</ul>